### ISSUE TITLE
api = sj.Shioaji() 一分鐘不回應然後錯誤，版本0.3.2.dev9

### ISSUE THREAD

**Issue by aga4gavin** [Sinotrade/Shioaji#112]
您好，我在Ubuntu 20.04測試，之前跑範例都沒問題，但這兩天在 api = sj.Shioaji() 執行時等待一分鐘不回應，然後印出下列Exception，請問是Server端的問題嗎？

版本為0.3.2.dev9

>>> import shioaji as sj
>>> api = sj.Shioaji()

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f04ca50a610>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='service.sinotrade.com.tw', port=443): Max retries exceeded with url: /api/v1/getClientIP (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f04ca50a610>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.8/site-packages/shioaji/shioaji.py", line 80, in __init__
    self._http = _http(False, proxies)
  File "shioaji/backend/http/main.pyx", line 16, in shioaji.backend.http.main.HttpApi.__init__
  File "shioaji/backend/http/client.pyx", line 60, in shioaji.backend.http.client.Client.__init__
  File "shioaji/backend/http/client.pyx", line 63, in shioaji.backend.http.client.Client.get_public_ip
  File "/home/user/.local/lib/python3.8/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='service.sinotrade.com.tw', port=443): Max retries exceeded with url: /api/v1/getClientIP (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f04ca50a610>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
>>>
>>>

**Comment by gavinage0** [comment]
好像是api.login因為在兩台機器同時測試，重複登入錯誤，現在好了!!
