### ISSUE TITLE
虛擬帳號無法登入

### ISSUE THREAD

**Issue by ccu516** [Sinotrade/Shioaji#120]
以下是虛擬帳號的登入碼:
```
import shioaji as sj
api = sj.Shioaji(simulation=False)
api.login(
    person_id="PAPIUSER02",
    passwd="2222",
    contracts_cb=lambda security_type: print(f"{repr(security_type)} fetch done.")
)
```
以下是錯誤訊息
```
"D:\Python\Python 3.7.7-64\Virtual_Env\Scripts\python.exe" "D:/Google Sync/同步用資料夾/程式語言/Python/Python_Taiwan_Stock_Trading_with_Shioaji/main.py"
Response Code: 0 | Event Code: 0 | Info: host '203.66.91.161:80', hostname '203.66.91.161:80' IP 203.66.91.161:80 (host 1 of 1) (host connection attempt 1 of 1) (total connection attempt 1 of 1) | Event: Session up
[22:57:29.172405] [5078203] [pysolace/core/sol.cpp:450:CSol::SendRequest] [E] [thread 8672] Incomplete
Traceback (most recent call last):
  File "D:/Google Sync/同步用資料夾/程式語言/Python/Python_Taiwan_Stock_Trading_with_Shioaji/main.py", line 15, in <module>
    contracts_cb=lambda security_type: print(f"{repr(security_type)} fetch done.")
  File "D:\Python\Python 3.7.7-64\Virtual_Env\lib\site-packages\shioaji\shioaji.py", line 138, in login
    accounts = self._solace.login(person_id, passwd, hashed)
  File "shioaji\backend\solace\api.pyx", line 322, in shioaji.backend.solace.api.SolaceAPI.login
  File "D:\Python\Python 3.7.7-64\Virtual_Env\lib\site-packages\shioaji\utils.py", line 50, in raise_resp_error
    raise Exception(resp)
Exception: {}
SDK NOTICE Sat Aug  7 22:57:29.172 2021 solClientCondition.c:376             (000021e0) solClient_session_sendRequest for session '(c0,s1)_sinopac', timed out waiting for request reply wait

```

**Comment by ypochien** [comment]
已修復，資源不足，測試環境比較不穩定 請見諒
