### ISSUE TITLE
憑證尚未生效無法使用

### ISSUE THREAD

**Issue by yiwunhuang** [Sinotrade/Shioaji#153]
我的服務要啟用在ubuntu的電腦上,
但是我看申請憑證那個e-lead是.exe檔
所以我先用了windows的電腦下載下來申請憑證得到Sinopac.pfx
再來就傳到ubuntu上面去

api.activate_ca(
    ca_path="/home/ubuntu/Sinopac.pfx",
    ca_passwd="預設的身分證ＩＤ",
    person_id="身分證ＩＤ"
)
這個會回 True
但是要下單的時候遇到下面的個錯誤：
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.10/site-packages/shioaji/shioaji.py", line 412, in place_order
    trade = self._solace.place_order(contract, order, timeout, cb)
  File "shioaji/backend/solace/api.pyx", line 912, in shioaji.backend.solace.api.SolaceAPI.place_order
  File "shioaji/backend/solace/api.pyx", line 370, in shioaji.backend.solace.api.SolaceAPI.prepare_ca
  File "shioaji/TWCA/ca.pyx", line 121, in shioaji.TWCA.ca.PyTWCASign.sign
  File "shioaji/TWCA/ca.pyx", line 124, in shioaji.TWCA.ca.PyTWCASign.gen_sign
  File "shioaji/TWCA/ca.pyx", line 113, in shioaji.TWCA.ca.PyTWCASign.get_quote_sign
  File "shioaji/TWCA/ca.pyx", line 109, in shioaji.TWCA.ca.PyTWCASign.get_sign
  File "shioaji/TWCA/ca.pyx", line 148, in shioaji.TWCA.ca.PyTWCASign.raise_error
shioaji.TWCA.ca.CaError: RTN_CERT_NOT_YET_VALID 5012 憑證尚未生效,無法使用

**Comment by yiwunhuang** [comment]
隔天找了營業員之後已解決
