### ISSUE TITLE
shioaji 套件引入測試專案無法執行的問題

### ISSUE THREAD

**Issue by crocodileci** [Sinotrade/Shioaji#167]
運行環境
OS:  MacOS 15.1 
Python版本: 3.12.7

使用官方的測試專案，引入shioaji套件至專案中

錯誤資訊如下 

Traceback (most recent call last):
  File "/Users/grady/Desktop/WorkSpace/sample project/Python/autotrade/sj-trading/.venv/bin/hello", line 7, in <module>
    from sj_trading import hello
  File "/Users/grady/Desktop/WorkSpace/sample project/Python/autotrade/sj-trading/src/sj_trading/__init__.py", line 1, in <module>
    import shioaji as sj
  File "/Users/grady/Desktop/WorkSpace/sample project/Python/autotrade/sj-trading/.venv/lib/python3.12/site-packages/shioaji/__init__.py", line 29, in <module>
    from shioaji.shioaji import Shioaji
  File "/Users/grady/Desktop/WorkSpace/sample project/Python/autotrade/sj-trading/.venv/lib/python3.12/site-packages/shioaji/shioaji.py", line 7, in <module>
    from shioaji.backend.solace.utils import (
  File "/Users/grady/Desktop/WorkSpace/sample project/Python/autotrade/sj-trading/.venv/lib/python3.12/site-packages/shioaji/backend/solace/__init__.py", line 1, in <module>
    from shioaji.backend.solace.api import SolaceAPI
  File "shioaji/backend/solace/api.pyx", line 9, in init shioaji.backend.solace.api
  File "/Users/grady/Desktop/WorkSpace/sample project/Python/autotrade/sj-trading/.venv/lib/python3.12/site-packages/pysolace/__init__.py", line 31, in <module>
    from pysolace import solclient
ImportError: dlopen(/Users/grady/Desktop/WorkSpace/sample project/Python/autotrade/sj-trading/.venv/lib/python3.12/site-packages/pysolace/solclient.cpython-312-darwin.so, 0x0002): Library not loaded: @rpath/libc++.1.dylib
  Referenced from: <E1502A14-FA52-388C-9982-FB1B6C69C659> /Users/grady/Desktop/WorkSpace/sample project/Python/autotrade/sj-trading/.venv/lib/python3.12/site-packages/pysolace/solclient.cpython-312-darwin.so
  Reason: tried: '/Users/ec666/miniconda3/envs/shioajipy312/lib/libc++.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/ec666/miniconda3/envs/shioajipy312/lib/libc++.1.dylib' (no such file), '/Users/ec666/miniconda3/envs/shioajipy312/lib/libc++.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/ec666/miniconda3/envs/shioajipy312/lib/libc++.1.dylib' (no such file), '/Users/grady/.pyenv/versions/3.12.7/lib/libc++.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/grady/.pyenv/versions/3.12.7/lib/libc++.1.dylib' (no such file), '/opt/homebrew/lib/libc++.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/libc++.1.dylib' (no such file), '/Users/grady/.pyenv/versions/3.12.7/lib/libc++.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/grady/.pyenv/versions/3.12.7/lib/libc++.1.dylib' (no such file), '/opt/homebrew/lib/libc++.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/libc++.1.dylib' (no such file)

請問我可以怎麼排除這個問題，正常使用shioaji 套件？

**Comment by Tsenyuuuu** [comment]
shioaji 的python 版本只支援3.6到3.11 你的python版本太高了 降版後試試看

**Comment by Yvictor** [comment]
https://sinotrade.github.io/zh_TW/env_setup/
請參考文件的環境認定
