### ISSUE TITLE
api.update_status()出現問題

### ISSUE THREAD

**Issue by luanya01** [Sinotrade/Shioaji#23]
windows 10
python 3.6.3 x64
-----

`api.update_status()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "d:\ide\workspace_python\xxx\lib\site-packages\shioaji\shioaji.py", line 330, in update_status
    self._api.update_status()
  File "shioaji\backend\http\main.pyx", line 117, in shioaji.backend.http.main.HttpApi.update_status
  File "shioaji\backend\http\order.pyx", line 104, in shioaji.backend.http.order.update_status
  File "shioaji\backend\http\stock\order.pyx", line 259, in shioaji.backend.http.stock.order.query_stock_order
  File "shioaji\backend\http\stock\order.pyx", line 240, in shioaji.backend.http.stock.order._query_stock_order
AttributeError: 'NoneType' object has no attribute 'broker_id'
`

**Comment by ypochien** [comment]
請更新 pip install shioaji -U
現在的版本已修復這樣的問題
