### ISSUE TITLE
何時會發生connection lost?

### ISSUE THREAD

**Issue by luanya01** [Sinotrade/Shioaji#26]
閒置一段時間(隔日)後會發生如下錯誤:

`
Exception in callback _SelectorTransport._call_connection_lost(ConnectionRes..., 10054, None))
handle: <Handle _SelectorTransport._call_connection_lost(ConnectionRes..., 10054, None))>
Traceback (most recent call last):
  File "d:\ide\Python\Python36_x64\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "d:\ide\Python\Python36_x64\lib\asyncio\selector_events.py", line 663, in _call_connection_lost
    self._protocol.connection_lost(exc)
  File "shioaji\backend\socket\connect.pyx", line 251, in shioaji.backend.socket.connect.Socket.connection_lost
AttributeError: 'Socket' object has no attribute '_logger'
`

**Comment by ypochien** [comment]
已修復

**Comment by KN16H7** [comment]
好像還是會斷:
  File "shioaji/backend/socket/connect.pyx", line 254, in shioaji.backend.socket.connect.Socket.connection_lost
AttributeError: 'Socket' object has no attribute '_logger'

[I 2019-12-29 06:18:06,024 /usr/local/lib/python3.6/site-packages/pyee/_compat.py:48:_emit_run] connection lost...
[I 2019-12-30 06:18:06,663 /usr/local/lib/python3.6/site-packages/pyee/_compat.py:48:_emit_run] connection lost...
