### ISSUE TITLE
module 'os' has no attribute 'add_dll_directory' in linux

### ISSUE THREAD

**Issue by sykuang** [Sinotrade/Shioaji#43]
Hi Yvictor,
I got error as below when I am trying to execute the example code.

```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import shioaji as sj
  File "/home/sykuang/.local/lib/python3.8/site-packages/shioaji/__init__.py", line 22, in <module>
    from shioaji.shioaji import Shioaji
  File "/home/sykuang/.local/lib/python3.8/site-packages/shioaji/shioaji.py", line 7, in <module>
    from shioaji.backend.solace import SolaceAPI
  File "/home/sykuang/.local/lib/python3.8/site-packages/shioaji/backend/solace/__init__.py", line 1, in <module>
    from shioaji.backend.solace.quote import Quote
  File "shioaji/backend/solace/quote.pyx", line 4, in init shioaji.backend.solace.quote
  File "/home/sykuang/.local/lib/python3.8/site-packages/pysolace/__init__.py", line 18, in <module>
    inject_lib_path()
  File "/home/sykuang/.local/lib/python3.8/site-packages/pysolace/__init__.py", line 15, in inject_lib_path
    os.add_dll_directory(libs_path.as_posix())
AttributeError: module 'os' has no attribute 'add_dll_directory'
Sentry is attempting to send 0 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
```

In pysolace/__init__.py
```
def inject_lib_path():
    import os
    import sys
    from pathlib import Path
    dir_path = Path(__file__).parent
    libs_path = dir_path.joinpath('.libs')
    os.environ["PATH"] = ";".join(
        [p for p in [os.environ.get("PATH", ""), libs_path.as_posix()] if p]
    )
    os.environ["LD_LIBRARY_PATH"] = ";".join(
        [p for p in [os.environ.get("LD_LIBRARY_PATH", ""),
                     libs_path.as_posix()] if p]
    )
    if sys.version_info.major == 3 and sys.version_info.minor >= 8:
        os.add_dll_directory(libs_path.as_posix())
```

You should add an os check for avoiding using add_dll_directory in Linux. I think add_dll_directory is for M$ windows.

**Comment by Yvictor** [comment]
0.3.0.dev0 fixed it.
