### ISSUE TITLE
MacBook Pro 執行 Simulation 失敗

### ISSUE THREAD

**Issue by lyenliang** [Sinotrade/Shioaji#55]
我照著[這頁](https://sinotrade.github.io/tutor/login/)執行以下的程式碼
```
import shioaji as sj
api = sj.Shioaji(simulation=True) 
api.login(
    person_id="PAPIUSER01", 
    passwd="2222", 
    contracts_cb=lambda security_type: print(f"{repr(security_type)} fetch done.")
)
```

結果得到底下的錯誤訊息：

```
/Users/my-user-name/.local/lib/python3.7/site-packages/shioaji/__init__.py:20: Warning: Mac OS currently don't provide ca module all function about placing order is not working.
  warnings.warn("Mac OS currently don't provide ca module all function about placing order is not working.", Warning)
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import shioaji as sj
  File "/Users/my-user-name/.local/lib/python3.7/site-packages/shioaji/__init__.py", line 26, in <module>
    from shioaji.shioaji import Shioaji
  File "/Users/my-user-name/.local/lib/python3.7/site-packages/shioaji/shioaji.py", line 5, in <module>
    from sentry_sdk import configure_scope
  File "/Users/my-user-name/.local/lib/python3.7/site-packages/sentry_sdk/__init__.py", line 1, in <module>
    from sentry_sdk.hub import Hub, init
  File "/Users/my-user-name/.local/lib/python3.7/site-packages/sentry_sdk/hub.py", line 9, in <module>
    from sentry_sdk.scope import Scope
  File "/Users/my-user-name/.local/lib/python3.7/site-packages/sentry_sdk/scope.py", line 6, in <module>
    from sentry_sdk.utils import logger, capture_internal_exceptions
  File "/Users/my-user-name/.local/lib/python3.7/site-packages/sentry_sdk/utils.py", line 791, in <module>
    HAS_REAL_CONTEXTVARS, ContextVar = _get_contextvars()
  File "/Users/my-user-name/.local/lib/python3.7/site-packages/sentry_sdk/utils.py", line 750, in _get_contextvars
    if not _is_threading_local_monkey_patched():
  File "/Users/my-user-name/.local/lib/python3.7/site-packages/sentry_sdk/utils.py", line 723, in _is_threading_local_monkey_patched
    from gevent.monkey import is_object_patched  # type: ignore
  File "/Users/my-user-name/anaconda3/lib/python3.7/site-packages/gevent/__init__.py", line 87, in <module>
    from gevent._hub_local import get_hub
  File "/Users/my-user-name/anaconda3/lib/python3.7/site-packages/gevent/_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "/Users/my-user-name/anaconda3/lib/python3.7/site-packages/gevent/_util.py", line 105, in import_c_accel
    mod = importlib.import_module(cname)
  File "/Users/my-user-name/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "src/gevent/__greenlet_primitives.pxd", line 12, in init gevent.__hub_local
ValueError: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 128 from PyObject
```

這個錯誤是不是跟蘋果電腦作業系統有關係？

**Comment by winthropchang** [comment]
Mac 環境下的 python 有很多版本
你在 command line 下輸入 which python 看看
看一下指向 python 的目錄位置是不是正確的

**Comment by winthropchang** [comment]
之前我也是使用 Mac 開發
可以登入 不過無法通過憑證認證
後來是在 Windows 環境下才成功的
