### ISSUE TITLE
list_positions failed

### ISSUE THREAD

**Issue by Ed-Yang** [Sinotrade/Shioaji#58]
In JupyterLab, after login and activate ca, run:

api.list_positions(api.stock_account)

Result:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-12216422eff5> in <module>
----> 1 api.list_positions(api.stock_account)

/opt/conda/lib/python3.8/site-packages/shioaji/shioaji.py in list_positions(self, account, timeout, cb)
    459         """
    460         if account:
--> 461             return self._solace.list_positions(account, timeout=timeout, cb=cb)
    462         else:
    463             if self.stock_account:

shioaji/backend/solace/api.pyx in shioaji.backend.solace.api.SolaceAPI.list_positions()

shioaji/backend/solace/api.pyx in shioaji.backend.solace.api.SolaceAPI._list_positions_cb()

/opt/conda/lib/python3.8/site-packages/shioaji/utils.py in raise_resp_error(status_code, resp)
     41 def raise_resp_error(status_code: int, resp: dict):
     42     log.error(resp)
---> 43     detail = resp.get("response", {}).get("detail", "")
     44     if status_code == 401:
     45         raise TokenError(status_code, detail)

AttributeError: 'str' object has no attribute 'get'

**Comment by Ed-Yang** [comment]
另外, set timeout=0

def pos_cb():
    print("called")
    
api.list_positions(api.stock_account, timeout=0, cb=pos_cb)


Result:

2020-08-20 01:59:24.133 | ERROR    | pysolace:onreply_callback_wrap:127 - An error has been caught in function 'onreply_callback_wrap', process 'MainProcess' (9), thread 'Dummy-4' (140565500380928):
Traceback (most recent call last):
> File "/opt/conda/lib/python3.8/site-packages/pysolace/__init__.py", line 122, in onreply_callback_wrap
    self.rep_callback_map.get(corrid, self.onreply_callback)(
    │    │                │   │       │    └ <function SolClient.__init__.<locals>.<lambda> at 0x7fd7ff5e09d0>
    │    │                │   │       └ <pysolace.SolClient object at 0x7fd82f4e8370>
    │    │                │   └ 'c19'
    │    │                └ <method 'get' of 'dict' objects>
    │    └ {'c17': <bound method SolaceAPI._list_positions_cb of <shioaji.backend.solace.api.SolaceAPI object at 0x7fd82f489d30>>, 'c19'...
    └ <pysolace.SolClient object at 0x7fd82f4e8370>
  File "shioaji/backend/solace/api.pyx", line 810, in shioaji.backend.solace.api.SolaceAPI._list_positions_cb
  File "/opt/conda/lib/python3.8/site-packages/shioaji/utils.py", line 43, in raise_resp_error
    detail = resp.get("response", {}).get("detail", "")
             │    └ <method 'get' of 'dict' objects>
             └ {'status': {'status_code': 500}, 'response': 'Internal Server Error'}

AttributeError: 'str' object has no attribute 'get'

**Comment by Ed-Yang** [comment]
> In JupyterLab, after login and activate ca, run:
> 
> api.list_positions(api.stock_account)
> 
> Result:
> 
> AttributeError Traceback (most recent call last)
> in 
> ----> 1 api.list_positions(api.stock_account)
> 
> /opt/conda/lib/python3.8/site-packages/shioaji/shioaji.py in list_positions(self, account, timeout, cb)
> 459 """
> 460 if account:
> --> 461 return self._solace.list_positions(account, timeout=timeout, cb=cb)
> 462 else:
> 463 if self.stock_account:
> 
> shioaji/backend/solace/api.pyx in shioaji.backend.solace.api.SolaceAPI.list_positions()
> 
> shioaji/backend/solace/api.pyx in shioaji.backend.solace.api.SolaceAPI._list_positions_cb()
> 
> /opt/conda/lib/python3.8/site-packages/shioaji/utils.py in raise_resp_error(status_code, resp)
> 41 def raise_resp_error(status_code: int, resp: dict):
> 42 log.error(resp)
> ---> 43 detail = resp.get("response", {}).get("detail", "")
> 44 if status_code == 401:
> 45 raise TokenError(status_code, detail)
> 
> AttributeError: 'str' object has no attribute 'get'

**Comment by Ed-Yang** [comment]
FYI

Check the log file, found the error log string is:

{'status': {'status_code': 500}, 'response': 'Internal Server Error'}

The line code: 

detail = resp.get("response", {}).get("detail", "")

The first part "resp.get("response", {})" will get str 'Internal Server Error' which is not a dict, so the follow ".get("detail", "")" will cause exception.

**Comment by Ed-Yang** [comment]
upgrade to 0.3.0.dev6 and restart JupyterLab, the problem is no more existed.
