### ISSUE TITLE
ImportError: DLL load failed while importing solclient: 動態連結程式庫 (DLL) 初始化例行程序失敗。

### ISSUE THREAD

**Issue by FangShinDeng** [Sinotrade/Shioaji#72]
您好，

我進行pip install shioaji成功後，使用了登入的範例結果報錯
`import shioaji as sj
api = sj.Shioaji(simulation=True) 
api.login(
    person_id="PAPIUSER01", 
    passwd="2222", 
    contracts_cb=lambda security_type: print(f"{repr(security_type)} fetch done.")
)`
![DDLerror](https://user-images.githubusercontent.com/45324337/98503244-fbcabb80-228e-11eb-8c2e-eec55dc1492c.png)

Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import shioaji as sj
  File "C:\Users\Mark\AppData\Local\Programs\Python\Python38\lib\site-packages\shioaji\__init__.py", line 26, in <module>
    from shioaji.shioaji import Shioaji
  File "C:\Users\Mark\AppData\Local\Programs\Python\Python38\lib\site-packages\shioaji\shioaji.py", line 10, in <module>
    from shioaji.backend.solace import SolaceAPI
  File "C:\Users\Mark\AppData\Local\Programs\Python\Python38\lib\site-packages\shioaji\backend\solace\__init__.py", line 1, in <module>
    from shioaji.backend.solace.api import SolaceAPI
  File "shioaji\backend\solace\api.pyx", line 9, in init shioaji.backend.solace.api
  File "C:\Users\Mark\AppData\Local\Programs\Python\Python38\lib\site-packages\pysolace\__init__.py", line 35, in <module>
    from pysolace import solclient
ImportError: DLL load failed while importing solclient: 動態連結程式庫 (DLL) 初始化例行程序失敗。

**Comment by FangShinDeng** [comment]
我使用Python 3.8.6的版本，請問是版本問題導致嗎？
還是我該如何解決呢

**Comment by nucweacia94fine** [comment]
> 我使用Python 3.8.6的版本，請問是版本問題導致嗎？
> 還是我該如何解決呢

具工程師所述，目前shioaji的兼容系統，Windows系統僅限Python 3.8以下，所以如果使用Windows系統，請改用Python 3.7.8。
