### ISSUE TITLE
api.login偶爾出現Exception

### ISSUE THREAD

**Issue by hamsterLiao** [Sinotrade/Shioaji#86]
進行登入時
`api.login(_id, secret)`

偶爾會得到以下Exception, 請問是什麼原因呢?

```
Exception ignored in: <function Shioaji.__del__ at 0x7f56ba8e33a0>
Traceback (most recent call last):
  File "/home/stock/anaconda3/envs/jupyter/lib/python3.8/site-packages/shioaji/shioaji.py", line 652, in __del__
    self._solace.__del__()
  File "shioaji/backend/solace/api.pyx", line 1232, in shioaji.backend.solace.api.SolaceAPI.__del__
  File "shioaji/backend/solace/api.pyx", line 327, in shioaji.backend.solace.api.SolaceAPI.logout
  File "/home/stock/anaconda3/envs/jupyter/lib/python3.8/site-packages/shioaji/utils.py", line 49, in raise_resp_error
    raise Exception(resp)
Exception: {}
```

**Comment by ypochien** [comment]
Timeout了, 登入的參數裡面預設是5000 太短了,您可以透過非同步=0 或者把這個值設定大一點
