### ISSUE TITLE
Sonipec－VNPY issue

### ISSUE THREAD

**Issue by regishsu** [Sinotrade/Shioaji#88]
Shioaji 0.3.1.dev8 搭配 Sonipec－vnpy，安裝sonipec-vnpy+python3.8可以下單，但是撤單會出現下面訊息，請問如何改code？

Traceback (most recent call last):
File "/home/regis/py_vm/vnpy_env/lib/python3.8/site-packages/vnpy/trader/ui/widget.py", line 451, in cancel_order
self.main_engine.cancel_order(req, order.gateway_name)
File "/home/regis/py_vm/vnpy_env/lib/python3.8/site-packages/vnpy/trader/engine.py", line 192, in cancel_order
gateway.cancel_order(req)
File "/home/regis/py_vm/vnpy_env/lib/python3.8/site-packages/vnpy/gateway/sinopac/sinopac_gateway.py", line 456, in cancel_order
self.api.cancel_order(self.orders[req.orderid])
File "/home/regis/py_vm/vnpy_env/lib/python3.8/site-packages/shioaji/shioaji.py", line 430, in cancel_order
trade = self._solace.cancel_order(trade, timeout, cb)
File "shioaji/backend/solace/api.pyx", line 524, in shioaji.backend.solace.api.SolaceAPI.cancel_order
File "shioaji/backend/solace/api.pyx", line 497, in shioaji.backend.solace.api.SolaceAPI._cancel_order_cb
File "/home/regis/py_vm/vnpy_env/lib/python3.8/site-packages/shioaji/utils.py", line 49, in raise_resp_error
raise Exception(resp)
Exception: {'status': {'status_code': 400}, 'response': {'detail': 'Please run update_status first to get trade details.'}}

**Comment by ian15937** [comment]
撤單前先執行api.update_status()
